/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import entidades.aluguel.AluguelFilmes;
import entidades.cadastros.Cliente;
import entidades.cadastros.Funcionario;
import entidades.enums.Status;
import entidades.filmes.Filmes;
import estatico.Dados;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedList;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class JDgAluguelDeFilmes extends javax.swing.JDialog {
    private LinkedList<Filmes> filmes = new LinkedList();
    
    private void esvaziaLista(){
        this.filmes = new LinkedList();
        return;
    }

    /**
     * Creates new form DJlAluguelDeFilmes
     */
    public JDgAluguelDeFilmes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregaDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPnInformacao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxFuncionario = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox();
        jpnInformacaoFun = new javax.swing.JPanel();
        lblNomeFuncionario = new javax.swing.JLabel();
        lblDepartamentoFuncionario = new javax.swing.JLabel();
        lblCpfFuncionario = new javax.swing.JLabel();
        jpnInformacaoCliente = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        lblCodigoCliente = new javax.swing.JLabel();
        lblCpfCliente = new javax.swing.JLabel();
        btnADicionarInformacao = new javax.swing.JButton();
        lblInformacaoProcesso = new javax.swing.JLabel();
        jpnInformacaoFimes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbxFilmes = new javax.swing.JComboBox();
        btnAdicionar = new javax.swing.JButton();
        jpnFilmesAlugar = new javax.swing.JPanel();
        lblCodigoFilme = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnConcluir = new javax.swing.JButton();
        jpnAluguel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Locação");
        setName("DjAluguel"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPnInformacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jLabel1.setText("Atendente");

        cbxFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFuncionarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente");

        cbxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClienteActionPerformed(evt);
            }
        });

        jpnInformacaoFun.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Funcionario"));

        javax.swing.GroupLayout jpnInformacaoFunLayout = new javax.swing.GroupLayout(jpnInformacaoFun);
        jpnInformacaoFun.setLayout(jpnInformacaoFunLayout);
        jpnInformacaoFunLayout.setHorizontalGroup(
            jpnInformacaoFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformacaoFunLayout.createSequentialGroup()
                .addGroup(jpnInformacaoFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnInformacaoFunLayout.createSequentialGroup()
                        .addComponent(lblCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDepartamentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblNomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnInformacaoFunLayout.setVerticalGroup(
            jpnInformacaoFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformacaoFunLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnInformacaoFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDepartamentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpnInformacaoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Cliente"));

        javax.swing.GroupLayout jpnInformacaoClienteLayout = new javax.swing.GroupLayout(jpnInformacaoCliente);
        jpnInformacaoCliente.setLayout(jpnInformacaoClienteLayout);
        jpnInformacaoClienteLayout.setHorizontalGroup(
            jpnInformacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformacaoClienteLayout.createSequentialGroup()
                .addComponent(lblCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCodigoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(jpnInformacaoClienteLayout.createSequentialGroup()
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnInformacaoClienteLayout.setVerticalGroup(
            jpnInformacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformacaoClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnInformacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnADicionarInformacao.setText("Adicionar");
        btnADicionarInformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADicionarInformacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnInformacaoLayout = new javax.swing.GroupLayout(jPnInformacao);
        jPnInformacao.setLayout(jPnInformacaoLayout);
        jPnInformacaoLayout.setHorizontalGroup(
            jPnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnInformacaoLayout.createSequentialGroup()
                .addGroup(jPnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblInformacaoProcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnInformacaoFun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnInformacaoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnInformacaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnInformacaoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
                            .addComponent(jpnInformacaoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnInformacaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnADicionarInformacao)
                        .addContainerGap())))
        );
        jPnInformacaoLayout.setVerticalGroup(
            jPnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnInformacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnInformacaoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnInformacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInformacaoProcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnADicionarInformacao))
                .addContainerGap())
        );

        jpnInformacaoFimes.setBorder(javax.swing.BorderFactory.createTitledBorder("Filmes"));

        jLabel3.setText("Escolha o filme");

        cbxFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFilmesActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jpnFilmesAlugar.setBorder(javax.swing.BorderFactory.createTitledBorder("Informação do filme"));

        javax.swing.GroupLayout jpnFilmesAlugarLayout = new javax.swing.GroupLayout(jpnFilmesAlugar);
        jpnFilmesAlugar.setLayout(jpnFilmesAlugarLayout);
        jpnFilmesAlugarLayout.setHorizontalGroup(
            jpnFilmesAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFilmesAlugarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnFilmesAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnFilmesAlugarLayout.createSequentialGroup()
                        .addComponent(lblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpnFilmesAlugarLayout.createSequentialGroup()
                        .addComponent(lblCodigoFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jpnFilmesAlugarLayout.setVerticalGroup(
            jpnFilmesAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFilmesAlugarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnFilmesAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodigoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConcluir.setText("Concluir");
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        jpnAluguel.setBorder(javax.swing.BorderFactory.createTitledBorder("Informação do aluguel"));

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane2.setViewportView(areaTexto);

        javax.swing.GroupLayout jpnAluguelLayout = new javax.swing.GroupLayout(jpnAluguel);
        jpnAluguel.setLayout(jpnAluguelLayout);
        jpnAluguelLayout.setHorizontalGroup(
            jpnAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jpnAluguelLayout.setVerticalGroup(
            jpnAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAluguelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnInformacaoFimesLayout = new javax.swing.GroupLayout(jpnInformacaoFimes);
        jpnInformacaoFimes.setLayout(jpnInformacaoFimesLayout);
        jpnInformacaoFimesLayout.setHorizontalGroup(
            jpnInformacaoFimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformacaoFimesLayout.createSequentialGroup()
                .addGroup(jpnInformacaoFimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnFilmesAlugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnInformacaoFimesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnInformacaoFimesLayout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jpnAluguel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnInformacaoFimesLayout.setVerticalGroup(
            jpnInformacaoFimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformacaoFimesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnInformacaoFimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnFilmesAlugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnInformacaoFimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnConcluir))
                .addContainerGap(67, Short.MAX_VALUE))
            .addComponent(jpnAluguel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnInformacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnInformacaoFimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnInformacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnInformacaoFimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        //Informação exibida no lblInformacaoProcesso
        lblInformacaoProcesso.setText("Por Favor Adicione um Atendente e Cliente para Continuar");
        btnAdicionar.setEnabled(false);
        btnConcluir.setEnabled(false);
       

        
        
        if(cbxFuncionario.getItemCount() == 0){
             lblNomeFuncionario.setText("Por favor Cadastre funcionario");
         }
        if(cbxCliente.getItemCount() == 0){
             lblNomeCliente.setText("Por favor Cadastre Cliente");
         }
         if(cbxFilmes.getItemCount() == 0){
             lblTitulo.setText("Sem Filmes Cadastrados!");
             return;
         }else{
             return;
         }    
            
        
    }//GEN-LAST:event_formWindowActivated
    private void carregaDados(){
        // carregando os valores para  o combo
        
        if(! estatico.Dados.getPessoas().isEmpty()){
                estatico.Dados.getPessoas().forEach((pessoas) ->{
                     if(pessoas instanceof Cliente){
                        cbxCliente.addItem(pessoas);
                     }else{
                        cbxFuncionario.addItem(pessoas);
                     }

                 });

            }
        if(! estatico.Dados.getFilmes().isEmpty()){
            estatico.Dados.getFilmes().forEach((filmes)->{
                cbxFilmes.addItem(filmes);
            });
        }
    }    
    
    private void cbxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFuncionarioActionPerformed
        // mostrar as infromações dos Funcionarios
        Funcionario funcionario = (Funcionario)cbxFuncionario.getSelectedItem();
        lblNomeFuncionario.setText("Nome: "+funcionario.getNome());
        lblDepartamentoFuncionario.setText("Dep: "+funcionario.getDepartamento().getNomeDepartamento());
        lblCpfFuncionario.setText("Cpf: "+funcionario.getCpf());
    }//GEN-LAST:event_cbxFuncionarioActionPerformed
    
    private void cbxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClienteActionPerformed
         // mostrar as infromações dos Funcionarios
        Cliente cliente = (Cliente)cbxCliente.getSelectedItem();
        lblNomeCliente.setText("Nome: "+cliente.getNome());
        lblCodigoCliente.setText("Código: "+cliente.getCodigo());
        lblCpfCliente.setText("Cpf: "+cliente.getCpf());
    }//GEN-LAST:event_cbxClienteActionPerformed

    private void btnADicionarInformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADicionarInformacaoActionPerformed
        // Mostra na area de texto os dados do cliente e atendente
        areaTexto.append(""+cbxCliente.getSelectedIndex());
        if((cbxCliente.getSelectedIndex() != -1) && (cbxFuncionario.getSelectedIndex() != -1)){
           Funcionario funcionario = (Funcionario)cbxFuncionario.getSelectedItem();
           Cliente cliente = (Cliente)cbxCliente.getSelectedItem();
            areaTexto.setText("Atendido por: " + funcionario.getNome() + "\n" +
                          "Cliente: " + cliente.getNome() + "   " + "Codigo: " + cliente.getCodigo() + "\n" +
                           "Cpf: " + cliente.getCpf() + "   " + "Telefone: " + cliente.getTelefone()+ "\n "
                                   + "-------------------------------------------------------------------------\n"); 
        
            lblInformacaoProcesso.setText("Insira Os Filmes!");
            btnAdicionar.setEnabled(true);
            esvaziaLista();
            
           }else{
                JOptionPane.showMessageDialog(null, "É necessario o cadastro do Atendente e Cliente");
                return;
           }
        
    }//GEN-LAST:event_btnADicionarInformacaoActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // adiciona os filmes na area de texto
        
        if(cbxFilmes.getSelectedIndex() !=  -1){
            Filmes filme = (Filmes)cbxFilmes.getSelectedItem();
            areaTexto.append("\n" + "Filme Alugado"+ "\n" + 
                            "Código: "+filme.getCodigo() + "\n" + 
                           "Titulo: " + filme.getTitulo() +"\n"+ "Genero: "+filme.getGenero() +
                            "Valor: " + filme.getPrecoAluguel()+"\n" + "-------------------------------------------------------------------------" );
            
            
            this.filmes.add(filme);
            btnConcluir.setEnabled(true);
            
            
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
       
        
        //datas de aluguel e entrega
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataAluguel = LocalDate.now();
        LocalDate dataEntrega = dataAluguel.plusDays(2);
        String dataEn = dataEntrega.format(formato);
        String dataAl = dataAluguel.format(formato);
        
        
        //Valor Total 
        double valorTotal = 0.0d;
        
        valorTotal = filmes.stream().map((filme) -> filme.getPrecoAluguel()).reduce(valorTotal, (accumulator, _item) -> accumulator + _item);
        // status do aluguel
        Status status = Status.END;
        
        // mostrando o restante das informações para o usuario e cliente;
        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance(new  Locale("pt", "br"));
        areaTexto.append("\n" + "-------Informações de entrega e valor\"-------" +"\n"+ 
                        " Valor total: " + formatoMoeda.format(valorTotal)+ "\n" + "Data Aluguel: "+ dataAl +
                        "\n" +"Data Entega: "+ dataEn   + "\n" + "Status: " + status);
        
        
        Funcionario funcionario = (Funcionario)cbxFuncionario.getSelectedItem();
        Cliente cliente = (Cliente)cbxCliente.getSelectedItem();
        
        btnConcluir.setEnabled(false);
        // criando e addicionando o objeto na lista 
        AluguelFilmes aluguel = new AluguelFilmes(funcionario, cliente, filmes, dataAluguel, dataEntrega, 
                        valorTotal, status);
        Dados.getAluguelfilmes().add(aluguel);
        btnAdicionar.setEnabled(false);
        esvaziaLista();
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void cbxFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFilmesActionPerformed
        Filmes filme = (Filmes)cbxFilmes.getSelectedItem();
            // colocando as informações nos label
            lblCodigoFilme.setText("Codigo: "+filme.getCodigo());
            lblTitulo.setText("Titulo: "+filme.getTitulo());
            lblGenero.setText("Genero: "+ filme.getGenero());
    }//GEN-LAST:event_cbxFilmesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDgAluguelDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDgAluguelDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDgAluguelDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDgAluguelDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDgAluguelDeFilmes dialog = new JDgAluguelDeFilmes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton btnADicionarInformacao;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnConcluir;
    private javax.swing.JComboBox cbxCliente;
    private javax.swing.JComboBox cbxFilmes;
    private javax.swing.JComboBox cbxFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPnInformacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jpnAluguel;
    private javax.swing.JPanel jpnFilmesAlugar;
    private javax.swing.JPanel jpnInformacaoCliente;
    private javax.swing.JPanel jpnInformacaoFimes;
    private javax.swing.JPanel jpnInformacaoFun;
    private javax.swing.JLabel lblCodigoCliente;
    private javax.swing.JLabel lblCodigoFilme;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblCpfFuncionario;
    private javax.swing.JLabel lblDepartamentoFuncionario;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblInformacaoProcesso;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
