/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import entidades.enums.Genero;
import entidades.filmes.Filmes;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Collections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class JDgFilmes extends javax.swing.JDialog {

    /**
     * Creates new form JDgFilmes
     */
    public JDgFilmes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProdutora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ftxDataLancamento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        rdbLancamento = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtPrecoAlocacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDuracao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtArtista = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JFormattedTextField();
        lblLogCAdastroFilmes = new javax.swing.JLabel();
        jpnConsultas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        btnFilmes = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Filmes");
        setName("Filmes"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Codigo");

        jLabel2.setText("Produtora");

        jLabel3.setText("Titulo");

        jLabel4.setText("Data Lançamento");

        try {
            ftxDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Genero");

        rdbLancamento.setText("Lançamento");

        jLabel7.setText("Preço Alocação");

        jLabel5.setText("Duração em minutos");

        jLabel8.setText("Artista");

        try {
            txtCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxDataLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProdutora))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecoAlocacao))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(rdbLancamento)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArtista))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(ftxDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoAlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbLancamento))
                .addGap(23, 23, 23))
        );

        jpnConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultas"));

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        btnFilmes.setText("Filmes Cadastrados");
        btnFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnConsultasLayout = new javax.swing.GroupLayout(jpnConsultas);
        jpnConsultas.setLayout(jpnConsultasLayout);
        jpnConsultasLayout.setHorizontalGroup(
            jpnConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
            .addGroup(jpnConsultasLayout.createSequentialGroup()
                .addComponent(btnFilmes)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnConsultasLayout.setVerticalGroup(
            jpnConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnConsultasLayout.createSequentialGroup()
                .addComponent(btnFilmes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogCAdastroFilmes))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(lblLogCAdastroFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //declaração de variaveil
        String codigo, produtora, artista, titulo;
        double pAlocacao;
        int duracao;
        
        // verificação das entradas de dados
        if(txtCodigo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtCodigo.requestFocus();
            return;
        }else{
            codigo = txtCodigo.getText();
        }
        
        if(txtProdutora.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtProdutora.requestFocus();
            return;
        }else{
            produtora = txtProdutora.getText();
        }
        
        if(txtTitulo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtTitulo.requestFocus();
            return;
        }else{
            titulo = txtTitulo.getText();
        }
        
        if(txtArtista.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtArtista.requestFocus();
            return;
        }else{
            artista = txtArtista.getText();
        }
        
        if(ftxDataLancamento.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            ftxDataLancamento.requestFocus();
            return;
        }
        
        if(txtPrecoAlocacao.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtPrecoAlocacao.requestFocus();
            return;
        }else{
            try{
                pAlocacao = Double.parseDouble(txtPrecoAlocacao.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Somente Numeros");
                txtPrecoAlocacao.requestFocus();
                return;
            }
        }
        
       if(txtDuracao.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtDuracao.requestFocus();
            return;
        }else{
            try{
                duracao = Integer.parseInt(txtDuracao.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Somente Numeros");
                txtDuracao.requestFocus();
                return;
            }
        }
       
       // pegando os valores dos combos
        Genero genero;
        genero = (Genero)cbxGenero.getSelectedItem();
        
        // instanciando uma data
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data;
        try{
            data = LocalDate.parse(ftxDataLancamento.getText(),formato);
        }catch(DateTimeParseException ex){
            JOptionPane.showMessageDialog(null, "Formato de data Invalida!");
            ftxDataLancamento.requestFocus();
            return;
        }
        
        Filmes filme = new Filmes(codigo, produtora, titulo, artista, data, duracao, 
                genero, pAlocacao, rdbLancamento.isSelected());
        
        estatico.Dados.getFilmes().add(filme);
        
        
        rdbLancamento.setSelected(false);
        txtDuracao.setText("");
        txtProdutora.setText("");
        txtArtista.setText("");
        ftxDataLancamento.setText("");
        txtTitulo.setText("");
        txtPrecoAlocacao.setText("");
        txtCodigo.setText("");
        txtCodigo.requestFocus();
        
        //mensagem
        areaTexto.setText("Filme Adicionado!");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // carregando os valorea do combo
        cbxGenero.setModel(new DefaultComboBoxModel(Genero.values()));
    }//GEN-LAST:event_formWindowActivated

    private void btnFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmesActionPerformed
        // Listagem dos filmes cadastrados
        
        if(estatico.Dados.getFilmes().isEmpty()){
            areaTexto.append("----------------------------Nenhum filme cadastrado!----------------------------");
        }
        
        // ordenando a lista de filmes
        Collections.sort(estatico.Dados.getFilmes(), (lista1, lista2)-> lista1.getTitulo().compareTo(lista2.getTitulo()));
        
        // criando um formato para a exibição das datas
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
        String data = null;
        // limpando o areatTexto
        areaTexto.setText("\n----------------------------Lista de  filmes cadastrados!----------------------------\n");
        //
        estatico.Dados.getFilmes().forEach(((filmes) -> {
            //Fonmatando o resultado do getLancamento da classe Filmes
            String lancamento;
            if(filmes.isLancamento()){
                lancamento = "Sim";
            }else{
                lancamento = "Não";
            }
            
            
            //Exibindo os cadastros para o usuario
            areaTexto.append("Código: " + filmes.getCodigo() + "\t" + "Produtora: " + filmes.getProdutora() + "\n"+
                    "Titulo : "+filmes.getTitulo() + "\t"+"Data LAnçamento: "+ filmes.getAnoLancamento().format(formato) + 
                  "\n"+ "Artista: " + filmes.getArtista() + "\n" + "Genero: " + filmes.getGenero() + "\t" + 
                    "Preço Alocação: " + filmes.getPrecoAluguel() + "\n" + "Duração: " + filmes.getDuracao() + "\t" +
                   "Lançamento: " + lancamento + "\n-----------------------------------------------------------------------------------\n" );
            
        }));
    }//GEN-LAST:event_btnFilmesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDgFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDgFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDgFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDgFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDgFilmes dialog = new JDgFilmes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFilmes;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JFormattedTextField ftxDataLancamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnConsultas;
    private javax.swing.JLabel lblLogCAdastroFilmes;
    private javax.swing.JRadioButton rdbLancamento;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JFormattedTextField txtCodigo;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtPrecoAlocacao;
    private javax.swing.JTextField txtProdutora;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
