/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import entidades.cadastros.Funcionario;
import composicao.Endereco;
import entidades.cadastros.Pessoa;
import entidades.enums.Cidades;
import entidades.enums.Departamento;
import entidades.enums.Estados;
import entidades.enums.Pais;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class JDlFuncionarios extends javax.swing.JDialog {

    /**
     * Creates new form JDlFuncionarios
     */
    public JDlFuncionarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jpnInformacoes = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        btnCadastrar = new javax.swing.JButton();
        jpnClienteEndereco = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxCidade = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbxPais = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ftxCep = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jpnCliente = new javax.swing.JPanel();
        ftxCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        ftxDataNascimento = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxDepartamento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        ftxTelefone = new javax.swing.JFormattedTextField();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Funcionario");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpnInformacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        javax.swing.GroupLayout jpnInformacoesLayout = new javax.swing.GroupLayout(jpnInformacoes);
        jpnInformacoes.setLayout(jpnInformacoesLayout);
        jpnInformacoesLayout.setHorizontalGroup(
            jpnInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jpnInformacoesLayout.createSequentialGroup()
                .addComponent(btnListar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnInformacoesLayout.setVerticalGroup(
            jpnInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformacoesLayout.createSequentialGroup()
                .addComponent(btnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jpnClienteEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel5.setText("Rua");

        jLabel7.setText("Bairro");

        jLabel8.setText("Cidade");

        jLabel9.setText("Estado");

        jLabel10.setText("Pais");

        jLabel11.setText("Cep");

        try {
            ftxCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Complemento");

        javax.swing.GroupLayout jpnClienteEnderecoLayout = new javax.swing.GroupLayout(jpnClienteEndereco);
        jpnClienteEndereco.setLayout(jpnClienteEnderecoLayout);
        jpnClienteEnderecoLayout.setHorizontalGroup(
            jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnClienteEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnClienteEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComplemento))
                    .addGroup(jpnClienteEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtRua))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnClienteEnderecoLayout.createSequentialGroup()
                        .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnClienteEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cbxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnClienteEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftxCep, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpnClienteEnderecoLayout.setVerticalGroup(
            jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnClienteEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(cbxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(ftxCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jpnCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Informação "));

        try {
            ftxCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Data Nascimento");

        try {
            ftxDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Nome");

        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setText("Cpf");

        jLabel12.setText("Salario");

        jLabel13.setText("Departamento");

        jLabel1.setText("Contato");

        jLabel14.setText("E-mail");

        try {
            ftxTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jpnClienteLayout = new javax.swing.GroupLayout(jpnCliente);
        jpnCliente.setLayout(jpnClienteLayout);
        jpnClienteLayout.setHorizontalGroup(
            jpnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnClienteLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addComponent(ftxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ftxDataNascimento))
                    .addGroup(jpnClienteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome))
                    .addGroup(jpnClienteLayout.createSequentialGroup()
                        .addGroup(jpnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnClienteLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail))
                            .addGroup(jpnClienteLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel13)))
                        .addGroup(jpnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnClienteLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(cbxDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpnClienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jpnClienteLayout.setVerticalGroup(
            jpnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnClienteLayout.createSequentialGroup()
                .addGroup(jpnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(ftxDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnClienteEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnClienteEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // Listagem de Funcionarios
        if(estatico.Dados.getPessoas().isEmpty()){
            areaTexto.setText("       -------------------------Sem Funcionarios cadastrados-------------------------");
            return;
        }
        areaTexto.setText("");
        // ordenando a lista de forma alfabetica
        Collections.sort(estatico.Dados.getPessoas(),(lista1, lista2) -> lista1.getNome().compareToIgnoreCase(lista2.getNome()));
        
        
        // mostrar os funcionarios ordenadamente usando as expressao lambda
        estatico.Dados.getPessoas().forEach((pessoas) ->{
            if(pessoas instanceof Funcionario){
            areaTexto.append("\n"+       "---------------------------Funcionario cadastrado---------------------------" +"\n");    
           
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            areaTexto.append("\n"+ "Nome: " + ((Funcionario) pessoas).getNome() + "\n" +
                "Cpf: " + pessoas.getCpf() +"\t"  + "Data Nascimento: " + sdf.format(pessoas.getDataNasct()) +"\n" +
                "Salario: "+ ((Funcionario) pessoas).getSalario() + "\t Departamento: "+((Funcionario) pessoas).getDepartamento()+"\n"+
                "E-mail: " + pessoas.getEmail() +"\t" + "Telefone: " + pessoas.getTelefone() +"\n"+
                "---------------------------Endereço Funcionario---------------------------"+"\n" +
                "Rua: "+ pessoas.getEndereco().getRua() + "\n" + "Bairro: "+ pessoas.getEndereco().getBairro()+ "\t" +
                "Complemento: " + pessoas.getEndereco().getComplemento()+"\n"+ "Cidade: " + pessoas.getEndereco().getCidade()+
                "\t" + "Estado: " + pessoas.getEndereco().getEstado()+"\n" + "Pais: " + pessoas.getEndereco().getPais()+
                    "\n" + "Cep: " + pessoas.getEndereco().getCep() + "\n" );
            }   

        });

        
       

        
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        // declaração de variaveis para criação de objeto Funcionario e composição
        String nome,cpf,email, telefone, rua, bairro, complemento,cep;
        double salario;

        // Validação dos campos de entrada
        if(txtNome.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtNome.requestFocus();
            return;
        }else{
            nome = txtNome.getText();
        }

        if(ftxCpf.getText().trim().length() < 14){
            JOptionPane.showMessageDialog(null, "Formato invalido");
            ftxCpf.requestFocus();
            return;
        }else{
            cpf = ftxCpf.getText();
        }

        if(ftxDataNascimento.getText().trim().length() < 10){
            JOptionPane.showMessageDialog(null, "Formato invalido");
            ftxDataNascimento.requestFocus();
            return;
        }
        
        if(txtSalario.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obricagotio");
            txtSalario.requestFocus();
            return;
        }else{
            try{
                salario = Double.parseDouble(txtSalario.getText());
            }catch(NumberFormatException ex){
               JOptionPane.showMessageDialog(null, "Formato invalido");
                txtSalario.requestFocus();
                return; 
            }
        }
        
        if(txtEmail.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtEmail.requestFocus();
            return;
        }else{
            email = txtEmail.getText();
        }
        
        if(ftxTelefone.getText().trim().length() < 13){
            JOptionPane.showMessageDialog(null, "Formato invalido");
            ftxTelefone.requestFocus();
            return;
        }else{
            telefone = ftxTelefone.getText();
        }

        // validação para campos da composição endereço
        if(txtRua.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtRua.requestFocus();
            return;
        }else{
            rua = txtRua.getText();
        }

        if(txtBairro.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtBairro.requestFocus();
            return;
        }else{
            bairro = txtBairro.getText();
        }

        if(txtComplemento.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Obrigatorio");
            txtComplemento.requestFocus();
            return;
        }else{
            complemento = txtComplemento.getText();
        }

        if(ftxCep.getText().trim().length() < 9){
            JOptionPane.showMessageDialog(null, "Formato invalido");
            ftxCep.requestFocus();
            return;
        }else{
            cep = ftxCep.getText();
        }

        // pegando os valores dos combos
        Departamento departamento;
        departamento = (Departamento)cbxDepartamento.getSelectedItem();
        Cidades cidade;
        cidade = (Cidades)cbxCidade.getSelectedItem();
        Estados estado;
        estado = (Estados)cbxEstado.getSelectedItem();
        Pais pais;
        pais = (Pais)cbxPais.getSelectedItem();

        // Data nascimento
        Date dataNascimento;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            dataNascimento = sdf.parse(ftxDataNascimento.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Data Invalida!");
            ftxDataNascimento.requestFocus();
            return;
        }

        // declarando a composição endereço
        Endereco endereco = new Endereco(rua, complemento, bairro, cidade, estado, pais, cep);

        //declarando objeto funcionario
        Pessoa funcionario = new Funcionario(departamento, salario, nome, cpf, email, telefone, dataNascimento, endereco);

        // inserindo na lista pessoa;
        estatico.Dados.getPessoas().add(funcionario);

        // limpando campos
        ftxCep.setText("");
        ftxDataNascimento.setText("");
        cbxPais.setSelectedIndex(0);
        cbxEstado.setSelectedIndex(0);
        cbxCidade.setSelectedIndex(0);
        txtComplemento.setText("");
        txtBairro.setText("");
        txtRua.setText("");
        cbxDepartamento.setSelectedIndex(0);
        ftxTelefone.setText("");
        txtEmail.setText("");
        txtSalario.setText("");
        ftxDataNascimento.setText("");
        ftxCpf.setText("");
        txtNome.setText("");
        txtNome.requestFocus();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carregando os dados para os combo box da classe enumeradores.
        
        cbxCidade.setModel(new DefaultComboBoxModel(Cidades.values()));
        cbxEstado.setModel(new DefaultComboBoxModel(Estados.values()));
        cbxPais.setModel(new DefaultComboBoxModel(Pais.values()));
        cbxDepartamento.setModel(new DefaultComboBoxModel(Departamento.values()));
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlFuncionarios dialog = new JDlFuncionarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> cbxCidade;
    private javax.swing.JComboBox<String> cbxDepartamento;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxPais;
    private javax.swing.JFormattedTextField ftxCep;
    private javax.swing.JFormattedTextField ftxCpf;
    private javax.swing.JFormattedTextField ftxDataNascimento;
    private javax.swing.JFormattedTextField ftxTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnCliente;
    private javax.swing.JPanel jpnClienteEndereco;
    private javax.swing.JPanel jpnInformacoes;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
