/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Antonio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        MBPrincipal = new javax.swing.JMenuBar();
        ITAlugar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ITDevolucao = new javax.swing.JMenuItem();
        JMCadastro = new javax.swing.JMenu();
        ITCliente = new javax.swing.JMenuItem();
        ITFuncionario = new javax.swing.JMenuItem();
        ITFilmes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Astro Video");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Frames/imagens/film.png")).getImage());
        setName("Principal"); // NOI18N
        setResizable(false);

        JPLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/imagens/log.jpg"))); // NOI18N

        javax.swing.GroupLayout JPLogoLayout = new javax.swing.GroupLayout(JPLogo);
        JPLogo.setLayout(JPLogoLayout);
        JPLogoLayout.setHorizontalGroup(
            JPLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPLogoLayout.setVerticalGroup(
            JPLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPLogoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ITAlugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/imagens/award_star_gold_1.png"))); // NOI18N
        ITAlugar.setText("Arquivos");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/imagens/cd.png"))); // NOI18N
        jMenuItem1.setText("Alugar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ITAlugar.add(jMenuItem1);

        ITDevolucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/imagens/arrow_undo.png"))); // NOI18N
        ITDevolucao.setText("Devolução");
        ITDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITDevolucaoActionPerformed(evt);
            }
        });
        ITAlugar.add(ITDevolucao);

        MBPrincipal.add(ITAlugar);

        JMCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/imagens/group_add.png"))); // NOI18N
        JMCadastro.setText("Cadastro");

        ITCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/imagens/user_add.png"))); // NOI18N
        ITCliente.setText("Cliente");
        ITCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITClienteActionPerformed(evt);
            }
        });
        JMCadastro.add(ITCliente);

        ITFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/imagens/group.png"))); // NOI18N
        ITFuncionario.setText("Funcionario");
        ITFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITFuncionarioActionPerformed(evt);
            }
        });
        JMCadastro.add(ITFuncionario);

        ITFilmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/imagens/film_add.png"))); // NOI18N
        ITFilmes.setText("Filmes");
        ITFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITFilmesActionPerformed(evt);
            }
        });
        JMCadastro.add(ITFilmes);

        MBPrincipal.add(JMCadastro);

        setJMenuBar(MBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ITClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITClienteActionPerformed
        // Carrega o jdlog cliente
        new JDgClientes(this, true).setVisible(true);
    }//GEN-LAST:event_ITClienteActionPerformed

    private void ITFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITFuncionarioActionPerformed
        // carrega o JDlFuncionario
        new JDlFuncionarios(this, true).setVisible(true);
    }//GEN-LAST:event_ITFuncionarioActionPerformed

    private void ITFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITFilmesActionPerformed
        // carrega o JDlfilmes
        new JDgFilmes(this, true).setVisible(true);
    }//GEN-LAST:event_ITFilmesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // carrega o JDllAluguelDeFilme
        new JDgAluguelDeFilmes(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ITDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITDevolucaoActionPerformed
        // carrega o JDgDevolucao
        new JDgDevolucao(this, true).setVisible(true);
    }//GEN-LAST:event_ITDevolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ITAlugar;
    private javax.swing.JMenuItem ITCliente;
    private javax.swing.JMenuItem ITDevolucao;
    private javax.swing.JMenuItem ITFilmes;
    private javax.swing.JMenuItem ITFuncionario;
    private javax.swing.JMenu JMCadastro;
    private javax.swing.JPanel JPLogo;
    private javax.swing.JMenuBar MBPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
